### ISSUE TITLE
Disable colors when node launched as Upstart daemon

### ISSUE THREAD

**Issue by mahnunchik** [sindresorhus/supports-color#14]
Chalk uses colors when node launched as Upstart daemon http://upstart.ubuntu.com/cookbook/#console-log

Sample of upstart config:
```
start on (started network-interface
          or started network-manager
          or started networking)

stop on (stopping network-interface
         or stopping network-manager
         or stopping networking)

respawn
env NODE_ENV=production

chdir /home/ubuntu/app
setuid ubuntu
setgid ubuntu

exec npm start

```

Logs are located in /var/log/upstart/app.log and they includes colors.

Stdout are detected by `supports-color` as TTY

https://github.com/sindresorhus/chalk/issues/48

Any ideas how to detect upstart?

**Comment by jdespatis** [comment]
Until the merge of this fix, I have no more color on my term (I have color before chalk 1.0.0)
Here is my upstart in my env:

```
UPSTART_JOB=startkde
```

Maybe it would be possible to check more precisely this UPSTART_JOB?

**Comment by sindresorhus** [comment]
@jdespatis https://github.com/sindresorhus/supports-color/issues/21#issuecomment-81580387

Just reinstall chalk to get it.

**Comment by jdespatis** [comment]
@sindresorhus yes thanks,
I've removed my node_modules and reinstall everything. It's ok now.
