### ISSUE TITLE
Supports Color breaks when using rewire

### ISSUE THREAD

**Issue by TheSavior** [sindresorhus/supports-color#23]
[Rewire](https://github.com/jhnns/rewire) adds a `__get__` and `__set__` to the internals of modules for people to use in tests.

Since supports-color's index.js file is wrapped in an IIFE, when it is required via a file that was 'rewired', we get the following error:
```
TypeError: Cannot assign to read only property '__get__' of true
```

**Comment by shubik22** [comment]
+1

**Comment by classiemilio** [comment]
+1

**Comment by sindresorhus** [comment]
It's the reverse though. Rewire breaking this module. Open an issue on Rewire instead. Returning a boolean instead of function in the export is totally valid.

**Comment by jbnicolai** [comment]
Couldn't agree more.
